### ISSUE TITLE
error $ is not a function. (ln '$(".shariff")'....

### ISSUE THREAD

**Issue by stefkey** [networkteam/Networkteam.Neos.Shariff#9]
Hi Networkteam,

my browser (dev-tools) shows an error:
$ is not a function. (In '$(".shariff")', '$' is "query")

in this file: Resources/Public/shariff/build/shariff.min.js

Is that a bug? How can I fix it?

**Comment by monofone** [comment]
Hey, jquery is missing, alternately you can include the shariff.complete.js, you can do this by altering the TS.

```
prototype(TYPO3.Neos:Page) {
    body.javascripts {
        shariff = TYPO3.TypoScript:Tag {
            tagName = 'script'
            attributes {
                src = TYPO3.TypoScript:ResourceUri {
                    path = 'resource://Networkteam.Neos.Shariff/Public/shariff/build/shariff.complete.js'
```

**Comment by stefkey** [comment]
Thanks a lot! It works!
